### PR TITLE
Allow passwords containing spaces

### LINKED ISSUE #15: Passwords with spaces
Hello

Skype accounts with passwords with a regular space (` `) in it does not work. I think this is due to:

https://github.com/Sorunome/mx-puppet-skype/blob/0255283d5aebbc8340d9f1ed389e3d91960925fe/src/index.ts#L120

I have tested to put the password in quotes but to no avail (_which is pretty logical I suppose_)

Thanks a lot !
Best regards

### PR DESCRIPTION
**Pull request by tchapi**
Adds a more complex regex to extract login/password info when the password contains a space

_On top of that, fix a typo and linting issues_

Should fix #15

### CODE REVIEW

**Comment by tchapi** [comment]
Does this PR match your need / style ? Do not hesitate if you need changes
Thanks !

**Comment by Sorunome** [comment]
Sorry for the late reply, just increadibly busy lately!

**Comment by tchapi** [comment]
Hi @Sorunome 
Do you think it would be possible to push the latest changes in the docker image ? I see it hasn't been updated in about 9 months

Thanks !

**Comment by Sorunome** [comment]
seems like the dockerfile broke, should be ok by now?

**Comment by tchapi** [comment]
Looks good, thanks !!

**Pull request merged**
